name: beautystar_user_app
description: Beautystar User App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Arcitechture
  stacked: ^1.2.2
  get: ^3.24.0
  auto_route: ^0.6.9
  stacked_services: ^0.6.7
  get_it: ^5.0.6
  injectable: ^1.0.7
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  # Networking
  dio: ^3.0.10
  connectivity: ^0.4.8+6

  # File & Image
  camera: ^0.5.8+2
  image_picker: ^0.6.7
  image: ^2.1.12
  flutter_image_compress: ^0.7.0
  mime: ^0.9.7
  photo_view: ^0.10.3
  image_cropper: ^1.3.1
  path_provider: ^1.6.9
  path: 
  
  # Other
  indonesia: ^1.0.1
  timeago: ^2.0.26
  toast: ^0.1.5
  url_launcher: ^5.5.0
  intl: ^0.16.0

  # Widget UI
  carousel_pro: ^1.0.0
  nx_flutter_ui_starter_pack: ^0.0.8

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  injectable_generator: ^1.0.7
  auto_route_generator: ^0.6.9
  hive_generator: ^0.8.2
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher.png"